/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ptithcm.voice_chat_server.views.frame;

import com.ptithcm.voice_chat_server.enums.ResponseStatus;
import com.ptithcm.voice_chat_server.models.Packet;
import com.ptithcm.voice_chat_server.models.Response;
import com.ptithcm.voice_chat_server.models.TCPClientSocket;
import com.ptithcm.voice_chat_server.store.SocketStore;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author minhd
 */
public class ManageFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManageFrame
     */
    public ManageFrame() {
        initComponents();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                for (TCPClientSocket client : SocketStore.tcpServerSocket.getTcpClientSocketManager().getClientSocketMap().values()) {
                    client.send(new Response(ResponseStatus.OK.getValue(), new Packet("disconnect", "Server is closed")), true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlServerCard = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlConnectedClients = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        scrollActionsOfSystem = new javax.swing.JScrollPane();
        pnlActionsOfSystem = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Voice Chat Server");
        setIconImage(new ImageIcon(getClass().getResource("/icons/_512x512/cpu-tower.png")).getImage());
        setPreferredSize(new java.awt.Dimension(1030, 500));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 90));
        jPanel2.setLayout(new java.awt.BorderLayout());

        pnlServerCard.setLayout(new java.awt.CardLayout());
        jPanel2.add(pnlServerCard, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.CardLayout(8, 16));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/_16x16/green_dot.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(32, 32));
        jPanel7.add(jLabel1, java.awt.BorderLayout.WEST);

        jLabel2.setText("DANH SÁCH MÁY TÍNH ĐANG KẾT NỐI");
        jPanel7.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(276, 276));

        pnlConnectedClients.setBackground(new java.awt.Color(255, 255, 255));
        pnlConnectedClients.setPreferredSize(new java.awt.Dimension(276, 0));
        jScrollPane1.setViewportView(pnlConnectedClients);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, "card2");

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(681, 88));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.CardLayout(8, 8));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/_64x64/terminal.png"))); // NOI18N
        jPanel11.add(jLabel3, "card2");

        jPanel9.add(jPanel11, java.awt.BorderLayout.WEST);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CÁC HOẠT ĐỘNG CỦA HỆ THỐNG ĐÃ VÀ ĐANG XẢY RA");
        jPanel12.add(jLabel4, "card2");

        jPanel9.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        scrollActionsOfSystem.setBackground(new java.awt.Color(255, 255, 255));
        scrollActionsOfSystem.setOpaque(false);
        scrollActionsOfSystem.setPreferredSize(new java.awt.Dimension(710, 0));

        pnlActionsOfSystem.setBackground(new java.awt.Color(39, 33, 33));
        pnlActionsOfSystem.setPreferredSize(new java.awt.Dimension(710, 100));
        scrollActionsOfSystem.setViewportView(pnlActionsOfSystem);

        jPanel3.add(scrollActionsOfSystem, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    Getter and setter
    public JPanel getPnlServerCard() {
        return pnlServerCard;
    }

    public void setPnlServerCard(JPanel pnlServerCard) {
        this.pnlServerCard = pnlServerCard;
    }

    public JPanel getPnlConnectedClients() {
        return pnlConnectedClients;
    }

    public void setPnlConnectedClients(JPanel pnlConnectedClients) {
        this.pnlConnectedClients = pnlConnectedClients;
    }

    public JPanel getPnlActionsOfSystem() {
        return pnlActionsOfSystem;
    }

    public void setPnlActionsOfSystem(JPanel pnlActionsOfSystem) {
        this.pnlActionsOfSystem = pnlActionsOfSystem;
    }

    public JScrollPane getScrollActionsOfSystem() {
        return scrollActionsOfSystem;
    }

    public void setScrollActionsOfSystem(JScrollPane scrollActionsOfSystem) {
        this.scrollActionsOfSystem = scrollActionsOfSystem;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlActionsOfSystem;
    private javax.swing.JPanel pnlConnectedClients;
    private javax.swing.JPanel pnlServerCard;
    private javax.swing.JScrollPane scrollActionsOfSystem;
    // End of variables declaration//GEN-END:variables
}
