/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.voice_chat_server.views.ui;

import javax.swing.ImageIcon;

/**
 *
 * @author minhd
 */
public class MessageUI extends javax.swing.JPanel {
    public static int height;
    
    /**
     * Creates new form MessageUI
     */
    public MessageUI(String iconPath, String message) {
        initComponents();
        height = (int) getPreferredSize().getHeight();
        lblIcon.setIcon(new ImageIcon(getClass().getResource(iconPath)));
        lblMessage.setText(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1000, 50));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.CardLayout(8, 8));

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/_16x16/green_dot.png"))); // NOI18N
        lblIcon.setPreferredSize(new java.awt.Dimension(32, 32));
        jPanel1.add(lblIcon, "card2");

        add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.CardLayout(8, 8));

        lblMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(51, 204, 0));
        lblMessage.setText("192.168.1.1 đã kết nối!");
        jPanel2.add(lblMessage, "card2");

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
