/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ptithcm.voice_chat_client.frame;

import com.ptithcm.voice_chat_client.enums.VoiceCallStatus;
import com.ptithcm.voice_chat_client.models.Fetch;
import com.ptithcm.voice_chat_client.models.Packet;
import com.ptithcm.voice_chat_client.models.Request;
import com.ptithcm.voice_chat_client.models.VoiceCall;
import com.ptithcm.voice_chat_client.store.ThreadStore;
import com.ptithcm.voice_chat_client.store.ViewStore;
import com.ptithcm.voice_chat_client.ui.CallerCardUI;
import java.util.Date;

/**
 *
 * @author minhd
 */
public class IcommingCallFrame extends javax.swing.JFrame {
    private VoiceCall voiceCall;

    /**
     * Creates new form CallFrame
     */
    public IcommingCallFrame(VoiceCall voiceCall) {
        initComponents();
        this.voiceCall = voiceCall;
        pnlCard.add(new CallerCardUI(voiceCall.getFrom()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAcceptTheCall = new javax.swing.JLabel();
        lblNotPickingUp = new javax.swing.JLabel();
        pnlCard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 350));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        lblAcceptTheCall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcceptTheCall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/_32x32/call.png"))); // NOI18N
        lblAcceptTheCall.setPreferredSize(new java.awt.Dimension(48, 48));
        lblAcceptTheCall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAcceptTheCallMouseClicked(evt);
            }
        });
        jPanel1.add(lblAcceptTheCall);

        lblNotPickingUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotPickingUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/_32x32/phone.png"))); // NOI18N
        lblNotPickingUp.setPreferredSize(new java.awt.Dimension(48, 48));
        lblNotPickingUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotPickingUpMouseClicked(evt);
            }
        });
        jPanel1.add(lblNotPickingUp);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pnlCard.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlCard, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNotPickingUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotPickingUpMouseClicked
        ThreadStore.endTask("Incomming-Call");
        voiceCall.setStatus(VoiceCallStatus.NOT_ANSWERING.getValue());
        new Fetch<VoiceCall, VoiceCall>(new Request(new Packet("Not-Answering", voiceCall)), VoiceCall.class).async();
        ViewStore.chatFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblNotPickingUpMouseClicked

    private void lblAcceptTheCallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAcceptTheCallMouseClicked
        ThreadStore.endTask("Incomming-Call");
        voiceCall.setStatus(VoiceCallStatus.PROGRESS.getValue());
        voiceCall.setCallAnswerTime(new Date());
        new Fetch<VoiceCall, VoiceCall>(new Request(new Packet("Accept-Call", voiceCall)), VoiceCall.class).async();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SingleCallFrame singleCallFrame = new SingleCallFrame(voiceCall.getFrom());
                singleCallFrame.setLocationRelativeTo(null);
                singleCallFrame.setVisible(true);
                
                new Fetch<VoiceCall, VoiceCall>(new Request(new Packet("Get-Current-Call", voiceCall)), VoiceCall.class).async();
            }
        });
        
        dispose();
    }//GEN-LAST:event_lblAcceptTheCallMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAcceptTheCall;
    private javax.swing.JLabel lblNotPickingUp;
    private javax.swing.JPanel pnlCard;
    // End of variables declaration//GEN-END:variables
}
