/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.voice_chat_client.ui;

import com.ptithcm.voice_chat_client.enums.ResponseStatus;
import com.ptithcm.voice_chat_client.enums.VoiceCallStatus;
import com.ptithcm.voice_chat_client.frame.SingleCallFrame;
import com.ptithcm.voice_chat_client.models.ClientInfo;
import com.ptithcm.voice_chat_client.models.Empty;
import com.ptithcm.voice_chat_client.models.EventGeneric;
import com.ptithcm.voice_chat_client.models.Fetch;
import com.ptithcm.voice_chat_client.models.Message;
import com.ptithcm.voice_chat_client.models.Packet;
import com.ptithcm.voice_chat_client.models.Request;
import com.ptithcm.voice_chat_client.models.Response;
import com.ptithcm.voice_chat_client.models.VoiceCall;
import com.ptithcm.voice_chat_client.store.SocketStore;
import com.ptithcm.voice_chat_client.store.ViewStore;
import java.awt.Dimension;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author minhd
 */
public class ChatUI extends javax.swing.JPanel {

    private ClientInfo receiver;

    /**
     * Creates new form ChatUI
     */
    public ChatUI(ClientInfo receiver) {
        initComponents();

        lbUuid.setText(receiver.getName());
        lbIp.setText(receiver.getIp());

        this.receiver = receiver;

        SocketStore.tcpClientSocket.registerEvent(new EventGeneric<Message[]>(SocketStore.tcpClientSocket, Message[].class)).on("Incoming-Message", (body) -> {
            pnlMessages.removeAll();

            for (Message message : body) {
                pnlMessages.add(new MessageUI(message));
            }

            pnlMessages.setPreferredSize(new Dimension(MessageUI.width, MessageUI.height * body.length));
            pnlMessages.revalidate();
            pnlMessages.repaint();
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        lbSend = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbUuid = new javax.swing.JLabel();
        lbIp = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblSingleVoiceCall = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlMessages = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout(10, 10));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout(5, 0));

        txtContent.setColumns(20);
        txtContent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContent.setRows(2);
        jScrollPane2.setViewportView(txtContent);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        lbSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/_24x24/send.png"))); // NOI18N
        lbSend.setPreferredSize(new java.awt.Dimension(32, 32));
        lbSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSendMouseClicked(evt);
            }
        });
        jPanel2.add(lbSend, java.awt.BorderLayout.EAST);

        jPanel5.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 4, 1));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        lbUuid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbUuid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbUuid.setText("192.168.1.2");
        jPanel3.add(lbUuid, java.awt.BorderLayout.PAGE_START);

        lbIp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbIp.setForeground(new java.awt.Color(0, 204, 0));
        lbIp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbIp.setText("192.168.1.2");
        jPanel3.add(lbIp, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        lblSingleVoiceCall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSingleVoiceCall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/_32x32/call.png"))); // NOI18N
        lblSingleVoiceCall.setPreferredSize(new java.awt.Dimension(48, 48));
        lblSingleVoiceCall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSingleVoiceCallMouseClicked(evt);
            }
        });
        jPanel4.add(lblSingleVoiceCall);

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        jPanel5.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.CardLayout());

        jScrollPane1.setBorder(null);

        pnlMessages.setBackground(new java.awt.Color(255, 255, 255));
        pnlMessages.setPreferredSize(new java.awt.Dimension(627, 0));
        pnlMessages.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(pnlMessages);

        jPanel6.add(jScrollPane1, "card2");

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        add(jPanel5, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void lbSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSendMouseClicked
        Message message = new Message(SocketStore.tcpClientSocket.getClientInfo(), receiver, txtContent.getText(), new Date(), new Date());
        Response<Empty> response = new Fetch<Message, Empty>(new Request(new Packet("Send-Message", message)), Empty.class).await().getResponse();
        if (response.getStatusCode() == ResponseStatus.OK.getValue()) {
            txtContent.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Unable to send message", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lbSendMouseClicked

    private void lblSingleVoiceCallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSingleVoiceCallMouseClicked
        ViewStore.chatFrame.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SingleCallFrame singleCallFrame = new SingleCallFrame(ViewStore.chatUI.getReceiver());
                new Fetch<VoiceCall, VoiceCall>(new Request(new Packet("Create-Single-Voice-Call", new VoiceCall(SocketStore.tcpClientSocket.getClientInfo(), ViewStore.chatUI.getReceiver(), VoiceCallStatus.DIALING.getValue(), new Date(), new Date()))), VoiceCall.class).async();
                singleCallFrame.setLocationRelativeTo(null);
                singleCallFrame.setVisible(true);
            }
        });
    }//GEN-LAST:event_lblSingleVoiceCallMouseClicked

//    Getters and setters
    public ClientInfo getReceiver() {
        return receiver;
    }

    public void setReceiver(ClientInfo receiver) {
        this.receiver = receiver;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbIp;
    private javax.swing.JLabel lbSend;
    private javax.swing.JLabel lbUuid;
    private javax.swing.JLabel lblSingleVoiceCall;
    private javax.swing.JPanel pnlMessages;
    private javax.swing.JTextArea txtContent;
    // End of variables declaration//GEN-END:variables
}
