/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.voice_chat_client.ui;

/**
 *
 * @author minhd
 */
public class MyUI extends javax.swing.JPanel {

    /**
     * Creates new form ServerHostUI
     */
    public MyUI(String id, String ip) {
        initComponents();
        lbId.setText(id);
        lbIp.setText(ip);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbId = new javax.swing.JLabel();
        lbIp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(330, 82));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.CardLayout(8, 8));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/_64x64/laptop.png"))); // NOI18N
        jPanel2.add(jLabel1, "card2");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/_64x64/laptop.png"))); // NOI18N
        jPanel2.add(jLabel2, "card3");

        add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        lbId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbId.setPreferredSize(new java.awt.Dimension(57, 48));
        jPanel3.add(lbId, java.awt.BorderLayout.NORTH);

        lbIp.setForeground(new java.awt.Color(0, 204, 0));
        lbIp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbIp.setPreferredSize(new java.awt.Dimension(57, 48));
        jPanel3.add(lbIp, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbIp;
    // End of variables declaration//GEN-END:variables
}
